name: mini-rag
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - faiss-cpu
  - pip
  - pip:
      - datasets
      - sentence-transformers
      - transformers
      - torch
      - pandas